### ISSUE TITLE
JWT verification 

### ISSUE THREAD

**Issue by ivborissov** [felipenoris/JWT.jl#10]
Hi, 
I am using the library to verify JWT for AWS
https://docs.aws.amazon.com/en_us/cognito/latest/developerguide/amazon-cognito-user-pools-using-tokens-verifying-a-jwt.html

I got suck with:
_"Use the public key to verify the signature using your JWT library. You might need to convert the JWK to PEM format first. This example takes the JWT and JWK, and uses the Node.js library, jsonwebtoken, to verify the JWT signature"_

I didn't find a Julia Pkg to convert JWK to PEM to use `JSONWebTokens.verify` then. 
How can signature verification be done using JWK in Julia?

**Comment by felipenoris** [comment]
Hi,

unfortunately I don't know any Julia package to handle JWKs. This could be a nice add-on to this package, if someone has the time to implement it.

If you want to stick to Julia to handle this logic, I guess you could code it by hand based on https://auth0.com/blog/navigating-rs256-and-jwks/ .

Cheers!
