### ISSUE TITLE
Roadmap to 1.0

### ISSUE THREAD

**Issue by DilumAluthge** [felipenoris/JWT.jl#15]
Are there any breaking changes to the public API that you would like to make before releasing JSONWebTokens version 1.0.0?

cc: @felipenoris

**Comment by felipenoris** [comment]
Given that the public API is only what is mentioned in the README file, there are no breaking changes I would like to do.
The only thing that keeps me from tagging v1.0 is the lack of features (see opened issues), which is not a blocker. If you need a v1.0 tag to help you out, I have no problem with that.

**Comment by DilumAluthge** [comment]
Sounds good, yeah it would be great to get a 1.0 release!

**Comment by DilumAluthge** [comment]
Bump @felipenoris any chance we could get a v1.0 tag?

**Comment by felipenoris** [comment]
@DilumAluthge sorry about the delay. Done!

**Comment by DilumAluthge** [comment]
No worries at all, thank you for the 1.0 tag and for the great package!
